# language-specific config

typemap:
    primitives:
        - byte: std::uint8_t
        - uint32: std::uint32_t
        - uint64: std::uint64_t
        - float: float
        - bool: bool
        - timestamp: std::time_t
        - string: std::string
        - uuid: boost::uuids::uuid
        - buffer: evb::Buffer
        - const-buffer: evb::ConstBuffer

    containers:
        - vector: 'std::vector<@>'
        - list: 'std::list<@>'
        - set: 'std::set<@>'
        - map: 'std::map<@, @>'

style:
    default:
        name-style: camelcase
        name-delimiter: ''
        name-use-short: false
        indent: 4

    namespace:
        name-delimiter: '::'
        name-style: lowercase
        indent: 2

    parameter:
        name-style: lowercase
        name-delimiter: '_'
        name-use-short: true

    enum:
        name-style: uppercase
  
    struct:
        indent: 6
        name-style: lowercase
        name-delimiter: '_'

    doc:
        text-wrap: 80

    class:
        name-style: uppercase
        name-delimiter: '+'

    operation:
        name-style: lowercase
        name-delimiter: '_'
